apiVersion: v1
kind: Service
metadata:
  name: wisecow
  namespace: wisecow
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  ports:
    - name: http
      port: 80
      targetPort: 4499
      protocol: TCP
